### ISSUE TITLE
老哥您好

### ISSUE THREAD

**Issue by GeartSun** [ChangxingJiang/CxSpider#6]
就针对脸书那个爬虫，配置文件需要配置什么，我看要事先从数据库读取一些链接吗，不是很懂学生小白

**Comment by GeartSun** [comment]
D:\code\CxSpider\venv\Scripts\python.exe D:/code/CxSpider/facebook/user_tweet.py
Traceback (most recent call last):
  File "D:/code/CxSpider/facebook/user_tweet.py", line 297, in <module>
    mysql_catalogue = tool.mysql_connect("huabang(old)")  # 构造MySQL数据库连接对象
  File "D:\code\CxSpider\toolkit\mysql.py", line 107, in connect
    return MySQL(host=env.MYSQL_INFO[name]["Host"],
KeyError: 'huabang(old)'

Process finished with exit code 1
